import { useCallback, useState } from 'react';
import { useAuth } from '@libs/react-shared';
import { errorMessage } from '@libs/utils';
import { UseFormSetError } from 'react-hook-form';
import type { MfaMethod } from '../sections/auth/mfa-method-select';
import type { MfaOtpFormValues } from '../sections/auth/mfa-otp-form';
import { ILoginSendOtpInput } from '@libs/types';

/**
 * Login flow step types
 */
export type LoginStep = 'login' | 'mfa-method' | 'mfa-verify';

/**
 * Login flow state interface
 */
export interface LoginFlowState {
    step: LoginStep;
    selectedMfaMethod: MfaMethod | null;
    availableMfaMethods: MfaMethod[];
    defaultMfaMethod: MfaMethod | null;
    loginCredentials: { email: string; password: string } | null;
    isLoading: boolean;
}

/**
 * Login flow actions interface
 */
export interface LoginFlowActions {
    handleLogin: (
        values: ILoginSendOtpInput,
        setError: UseFormSetError<ILoginSendOtpInput>
    ) => Promise<void>;
    handleMfaMethodSelect: (method: MfaMethod) => Promise<void>;
    handleMfaVerify: (
        values: MfaOtpFormValues,
        setError: UseFormSetError<MfaOtpFormValues>
    ) => Promise<void>;
    handleMfaResend: (
        setError: UseFormSetError<MfaOtpFormValues>
    ) => Promise<void>;
    handleBackToMethod: () => void;
    handleBackToLogin: () => void;
    canResendCode: () => boolean;
}

/**
 * Map API MFA method names to MfaMethod type
 */
const mapMfaMethod = (method: string): MfaMethod => {
    switch (method?.toLowerCase()) {
        case 'email':
            return 'email';
        case 'sms':
        case 'phone':
            return 'phone';
        case 'totp':
            return 'totp';
        default:
            return 'email';
    }
};

/**
 * Map MfaMethod back to API format for sending codes
 */
const mapToApiMfaMethod = (method: MfaMethod): 'email' | 'phone' => {
    switch (method) {
        case 'email':
            return 'email';
        case 'phone':
            return 'phone';
        case 'totp':
            // TOTP doesn't need to send code, but use email as fallback for API
            return 'email';
        default:
            return 'email';
    }
};

/**
 * Custom hook to manage the login flow with MFA support
 *
 * This hook handles:
 * - Initial login with email/password
 * - MFA method selection (when multiple methods available)
 * - MFA verification (OTP input)
 * - Automatic flow management based on default MFA method
 * - Trust device functionality to skip MFA on future logins
 *
 * Flow logic:
 * 1. If login requires MFA and a default method is set:
 *    - Skip method selection, go directly to verification
 *    - Send code automatically for email/phone (not for TOTP)
 * 2. If login requires MFA with no default or multiple methods:
 *    - Show method selection screen
 * 3. User can switch methods from verification screen
 * 4. If "Remember this device" is checked, trustDevice=true is sent
 *    to skip MFA on future logins for a configured period
 */
export function useLoginFlow(): LoginFlowState & LoginFlowActions {
    const { login, client, send2fa } = useAuth();

    const [step, setStep] = useState<LoginStep>('login');
    const [selectedMfaMethod, setSelectedMfaMethod] = useState<MfaMethod | null>(null);
    const [availableMfaMethods, setAvailableMfaMethods] = useState<MfaMethod[]>([]);
    const [defaultMfaMethod, setDefaultMfaMethod] = useState<MfaMethod | null>(null);
    const [loginCredentials, setLoginCredentials] = useState<{ email: string; password: string } | null>(null);
    const [isLoading, setIsLoading] = useState(false);

    /**
     * Check if the current method supports resending codes
     * TOTP codes are generated by the authenticator app, not sent by server
     */
    const canResendCode = useCallback(() => {
        return selectedMfaMethod !== 'totp';
    }, [selectedMfaMethod]);

    /**
     * Send 2FA code for the given method
     * Skips sending for TOTP since codes come from authenticator app
     */
    const sendCodeForMethod = useCallback(async (method: MfaMethod) => {
        if (method === 'totp') {
            // TOTP codes are generated by authenticator app, no need to send
            return;
        }
        try {
            await send2fa(mapToApiMfaMethod(method));
        } catch (error) {
            // Code might have been sent already, continue to verification
            console.warn('Failed to send 2FA code:', error);
        }
    }, [send2fa]);

    /**
     * Process MFA requirement from login response
     */
    const processMfaRequired = useCallback(async (
        mfaMethods: string[],
        defaultMethod: string | null | undefined,
        credentials: { email: string; password: string }
    ) => {
        setLoginCredentials(credentials);

        const methods = mfaMethods.map(mapMfaMethod);
        setAvailableMfaMethods(methods);

        const mappedDefault = defaultMethod ? mapMfaMethod(defaultMethod) : null;
        setDefaultMfaMethod(mappedDefault);

        // If default method is set and available, go directly to verification
        if (mappedDefault && methods.includes(mappedDefault)) {
            setSelectedMfaMethod(mappedDefault);
            await sendCodeForMethod(mappedDefault);
            setStep('mfa-verify');
        }
        // If only one method available, use it directly
        else if (methods.length === 1) {
            setSelectedMfaMethod(methods[0]);
            await sendCodeForMethod(methods[0]);
            setStep('mfa-verify');
        }
        // Multiple methods without default, show selection
        else {
            setStep('mfa-method');
        }
    }, [sendCodeForMethod]);

    /**
     * Handle initial login
     */
    const handleLogin = useCallback(async (
        values: ILoginSendOtpInput,
        setError: UseFormSetError<ILoginSendOtpInput>
    ) => {
        setIsLoading(true);
        try {
            const response = await login({
                providerName: 'email',
                credentials: values,
            });

            // Check if MFA is required
            if (response?.isRequiresMfa) {
                await processMfaRequired(
                    response.mfaMethods || [],
                    response.defaultMfaMethod as string,
                    values
                );
            }
            // If no MFA, login is complete (handled by auth context)
        } catch (error: any) {
            // Check if error response indicates MFA is required
            const errorData = error?.response?.data || error?.data;
            if (errorData?.isRequiresMfa) {
                await processMfaRequired(
                    errorData.mfaMethods || [],
                    errorData.defaultMfaMethod,
                    values
                );
            } else {
                setError('afterSubmit' as any, {
                    type: 'manual',
                    message: errorMessage(error),
                });
            }
        } finally {
            setIsLoading(false);
        }
    }, [login, processMfaRequired]);

    /**
     * Handle MFA method selection
     */
    const handleMfaMethodSelect = useCallback(async (method: MfaMethod) => {
        setSelectedMfaMethod(method);
        setIsLoading(true);
        try {
            await sendCodeForMethod(method);
            setStep('mfa-verify');
        } finally {
            setIsLoading(false);
        }
    }, [sendCodeForMethod]);

    /**
     * Handle MFA OTP verification
     * Passes trustDevice to the API to enable "Remember this device" functionality
     */
    const handleMfaVerify = useCallback(async (
        values: MfaOtpFormValues,
        setError: UseFormSetError<MfaOtpFormValues>
    ) => {
        setIsLoading(true);
        try {
            await client.verify2fa({
                otp: values.otp,
                method: selectedMfaMethod as any,
                trustDevice: values.trustDevice,
            });
            // Success - the auth context will handle the authenticated state
        } catch (error) {
            setError('root', {
                type: 'manual',
                message: errorMessage(error),
            });
        } finally {
            setIsLoading(false);
        }
    }, [client, selectedMfaMethod]);

    /**
     * Handle resending MFA code
     */
    const handleMfaResend = useCallback(async (
        setError: UseFormSetError<MfaOtpFormValues>
    ) => {
        if (!canResendCode()) {
            return;
        }

        setIsLoading(true);
        try {
            if (selectedMfaMethod) {
                await client.send2fa(mapToApiMfaMethod(selectedMfaMethod));
            }
        } catch (error) {
            setError('root', {
                type: 'manual',
                message: errorMessage(error),
            });
        } finally {
            setIsLoading(false);
        }
    }, [client, selectedMfaMethod, canResendCode]);

    /**
     * Navigate back to method selection
     */
    const handleBackToMethod = useCallback(() => {
        setStep('mfa-method');
    }, []);

    /**
     * Navigate back to login and reset state
     */
    const handleBackToLogin = useCallback(() => {
        setStep('login');
        setSelectedMfaMethod(null);
        setLoginCredentials(null);
        setAvailableMfaMethods([]);
        setDefaultMfaMethod(null);
    }, []);

    return {
        // State
        step,
        selectedMfaMethod,
        availableMfaMethods,
        defaultMfaMethod,
        loginCredentials,
        isLoading,

        // Actions
        handleLogin,
        handleMfaMethodSelect,
        handleMfaVerify,
        handleMfaResend,
        handleBackToMethod,
        handleBackToLogin,
        canResendCode,
    };
}

export default useLoginFlow;
