#!/usr/bin/env node

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { DEFAULT_TEMPLATE } from './config/default-template.mjs';
import { parseSimpleYaml, resolvePlaceholders } from './utils/simple-yaml.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

const SOURCE_PATH = path.join(ROOT, 'config', 'app.yml');
const TARGET_PATH = path.join(ROOT, 'libs', 'app-config', 'src', 'app-config.generated.ts');

let parsedYaml = {};
if (fs.existsSync(SOURCE_PATH)) {
    const yamlContent = fs.readFileSync(SOURCE_PATH, 'utf8');
    parsedYaml = parseSimpleYaml(yamlContent);
} else {
    console.warn('Configuration file missing at', path.relative(ROOT, SOURCE_PATH), '- using default template.');
}

const mergedConfig = deepMerge(clone(DEFAULT_TEMPLATE), parsedYaml);
const resolvedConfig = resolvePlaceholders(mergedConfig);

const runtimeConfig = {
    apiUrl: resolvedConfig?.urls?.api ?? '',
    webUrl: resolvedConfig?.urls?.web ?? '',
    frontUrl: resolvedConfig?.urls?.web ?? '',
    adminUrl: resolvedConfig?.urls?.admin ?? '',
    cdnUrl: resolvedConfig?.urls?.cdn ?? '',
    appName: resolvedConfig?.app?.name ?? '',
    appDescription: resolvedConfig?.app?.description ?? '',
    features: resolvedConfig?.features ?? {},
};

const fileHeader = `/* eslint-disable */\n// This file is auto-generated by scripts/generate-config.mjs.\n// Do not edit this file directly. Update config/app.yml instead.\n\n`;

const generated = `${fileHeader}export const appConfig = ${JSON.stringify(resolvedConfig, null, 4)} as const;\n\nexport const runtimeConfig = ${JSON.stringify(runtimeConfig, null, 4)} as const;\n\nexport type AppConfig = typeof appConfig;\nexport type RuntimeConfig = typeof runtimeConfig;\n`;

fs.mkdirSync(path.dirname(TARGET_PATH), { recursive: true });
fs.writeFileSync(TARGET_PATH, generated);
console.log('Generated app configuration at', path.relative(ROOT, TARGET_PATH));

function deepMerge(target, source) {
    const output = Array.isArray(target) ? [...target] : { ...target };
    if (!source || typeof source !== 'object') {
        return output;
    }

    Object.entries(source).forEach(([key, value]) => {
        if (value && typeof value === 'object' && !Array.isArray(value)) {
            output[key] = deepMerge(output[key] ?? {}, value);
        } else {
            output[key] = value;
        }
    });

    return output;
}

function clone(value) {
    return JSON.parse(JSON.stringify(value ?? {}));
}
